apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0f04aaaf02b44383d
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-efs-pvc
spec:
  volumeName: expense-efs-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi