apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-pvc
spec:
  storageClassName: "expense-efs-sc" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic-pod
  labels:
    purpose: efs-dynamic
spec:
  #nodeSelector:
  # topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: efs-dynamic
      mountPath: /usr/share/nginx/html
  volumes:
  - name: efs-dynamic
    persistentVolumeClaim:
      claimName: efs-dynamic-pvc

---
kind: Service 
apiVersion: v1
metadata: 
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic
  ports:
  - name: nginx-svc-port 
    protocol: TCP 
    port: 80
    targetPort: 80
    nodePort: 30007
